/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ColumnNamingEntry: typeof import('./components/data-wrangler/ColumnNamingEntry.vue')['default']
    CommonTransformationPanelFormButtons: typeof import('./components/data-wrangler/CommonTransformationPanelFormButtons.vue')['default']
    CountMatchTransformation: typeof import('./components/data-wrangler/transformations/CountMatchTransformation.vue')['default']
    CustomScalaTransformation: typeof import('./components/data-wrangler/transformations/CustomScalaTransformation.vue')['default']
    CustomSqlTransformation: typeof import('./components/data-wrangler/transformations/CustomSqlTransformation.vue')['default']
    DataTable: typeof import('./components/DataTable.vue')['default']
    DownloadTable: typeof import('./components/data-wrangler/transformations/DownloadTable.vue')['default']
    DropColumnTransformation: typeof import('./components/data-wrangler/transformations/DropColumnTransformation.vue')['default']
    EmptyTransformation: typeof import('./components/data-wrangler/transformations/EmptyTransformation.vue')['default']
    FilterColumnsTransformation: typeof import('./components/data-wrangler/transformations/FilterColumnsTransformation.vue')['default']
    FilterRowsTransformation: typeof import('./components/data-wrangler/transformations/FilterRowsTransformation.vue')['default']
    FormatStringTransformation: typeof import('./components/data-wrangler/transformations/FormatStringTransformation.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HelpTaggedEntry: typeof import('./components/data-wrangler/HelpTaggedEntry.vue')['default']
    MergeColumnTransformation: typeof import('./components/data-wrangler/transformations/MergeColumnTransformation.vue')['default']
    MonacoEditor: typeof import('./components/data-wrangler/MonacoEditor.vue')['default']
    RenameColumnTransformation: typeof import('./components/data-wrangler/transformations/RenameColumnTransformation.vue')['default']
    ReplaceRowValueTransformation: typeof import('./components/data-wrangler/transformations/ReplaceRowValueTransformation.vue')['default']
    ResetTableStepWarningMessage: typeof import('./components/data-wrangler/ResetTableStepWarningMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveToDeltaTable: typeof import('./components/data-wrangler/transformations/SaveToDeltaTable.vue')['default']
    SelectDatasetDialog: typeof import('./components/data-wrangler/SelectDatasetDialog.vue')['default']
    ShowColInfo: typeof import('./components/data-wrangler/ShowColInfo.vue')['default']
    SplitColumnTransformation: typeof import('./components/data-wrangler/transformations/SplitColumnTransformation.vue')['default']
    TabViewScaffold: typeof import('./components/TabViewScaffold.vue')['default']
    TransformationHelp: typeof import('./components/data-wrangler/TransformationHelp.vue')['default']
    TransformationOptions: typeof import('./components/data-wrangler/TransformationOptions.vue')['default']
    TransformationPanel: typeof import('./components/data-wrangler/TransformationPanel.vue')['default']
    TypeCastTransformation: typeof import('./components/data-wrangler/transformations/TypeCastTransformation.vue')['default']
    WranglerTopRightButtonGroup: typeof import('./components/data-wrangler/WranglerTopRightButtonGroup.vue')['default']
  }
}
